sudo zypper install --no-confirm firefox
sudo zypper install --no-confirm git
sudo zypper install --no-confirm neovim
sudo zypper install --no-confirm go
sudo zypper install --no-confirm gopls
sudo zypper install --no-confirm gh
sudo zypper install --no-confirm glab
sudo zypper install --no-confirm telegram-desktop
sudo zypper install --no-confirm iosevka-fonts
sudo zypper install --no-confirm htop
sudo zypper install --no-confirm make
sudo zypper install --no-confirm wezterm
